package.json
src/pages/Home/Home.tsx

test: 배포테스트

---

src/pages/Signup/index.tsx

[회원가입 페이지] 서버에러 500 나던거 수정
- [x ] 버그 수정
- 회원가입시 에러나는 부분을 수정했습니다.
- 서버에서 data 받을 때 formData로 받고 있어서 formData로 변환 후 전송하는 방식으로 바꾸었습니다.

fix: 회원가입 에러 해결/ form data 변환

---

src/components/Input/input.module.scss
src/pages/Signup/signup.module.scss

fix: scss stylelint 에러 해결

---

src/pages/Signup/index.tsx
src/pages/Signup/signup.module.scss

fix: 텍스트, 버튼 스타일 수정
- 회원가입 -> 다음으로 텍스트 수정
- 중복확인 버튼 크기, 위치 수정

fix: 텍스트, 버튼 스타일 수정

---

src/pages/Signup/index.tsx
src/pages/Signup/signup.module.scss

회원가입 닉네임중복 에러 부분 수정
- 닉네임 수정시 안내 문구 null 처리
- 버튼, 텍스트 색 분기 처리

fix: 회원가입 닉네임중복 에러 부분 수정

---

src/components/Detail/Comment/ReplyComment/index.tsx
src/components/Detail/Comment/SingleComment/index.tsx
src/components/Detail/Comment/comment.module.scss
src/components/Detail/Comment/index.tsx
src/components/Detail/DetailContent/index.tsx
src/components/Input/input.module.scss
src/pages/Signup/index.tsx
src/styles/constants/_colors.scss

댓글 컴포넌트, eslint 수정
- 댓글 컴포넌트를 댓글, 대댓글로 만들었습니다.
- 현재 인풋창에 댓글쓰고 엔터치면 content만 추가되게 작업해놨는데 api붙이면 구조를 좀 수정해야 될 것 같기도하고.. 그렇습니다.
- eslint 경고 부분 수정했습니다

fix: 댓글 컴포넌트, eslint 수정

---

public/index.html

fix: 불필요한 공백 제거

---

src/pages/Home/index.tsx

test: 배포 테스트

---

src/components/Detail/DetailContent/index.tsx
src/pages/Detail/index.tsx
src/pages/Home/index.tsx
src/pages/Signup/index.tsx

detail 페이지 api 연동 테스트
- 노션에 정리가 덜 된 것같아 data에 찍히는 내용 기반으로 테스트 했습니다.

feat: detail 페이지 api 연동 테스트

---

src/components/Detail/Comment/index.tsx
src/components/Detail/DetailContent/index.tsx
src/pages/Signup/index.tsx

불필요한 type 삭제, detail 페이지 수정
- 피드백 반영하여 수정했습니다
- 없는 상세페이지일때 alert -> error페이지로 변경했습니다

fix: 불필요한 type 삭제, detail 페이지 수정

---

src/pages/Signup/index.tsx
src/pages/Signup/signup.module.scss

회원가입 롤백 부분 수정
- pull 받고 롤백 된 부분 수정했습니다

fix: 회원가입 롤백 부분 수정

---

src/components/Button/button.module.scss
src/components/Button/index.tsx
src/components/Detail/Comment/ReplyComment/index.tsx
src/components/Detail/Comment/SingleComment/index.tsx
src/components/Detail/Comment/comment.module.scss
src/components/Detail/Comment/index.tsx
src/components/ErrorMessage/errorMessage.module.scss
src/components/ErrorMessage/index.tsx
src/components/Input/input.module.scss
src/hooks/useComment.ts
src/hooks/useCommentReply.ts
src/pages/Detail/index.tsx
src/pages/Signup/index.tsx
src/pages/Signup/signup.module.scss
src/styles/constants/_colors.scss
src/types/index.d.ts

댓글 query 추가, 버튼, 에러메세지 컴포넌트 추가
- secondary 버튼 컴포넌트 추가했습니다. secondary가 기본이 될 때가 있어야해서 그부분도 작업했습니다.
- ErrorMessage 컴포넌트 추가했습니다.
- 버튼 회색이 바껴서 colors에서 추가해 변경해놓았습니다.
- 댓글 query 추가했고 작업중입니다.

feat: 댓글 query 추가, 버튼, 에러메세지 컴포넌트 추가

---

src/components/Detail/Comment/ReplyComment/index.tsx
src/components/Detail/Comment/SingleComment/index.tsx
src/components/Detail/Comment/comment.module.scss
src/components/Detail/Comment/index.tsx
src/types/index.d.ts

댓글 기능 추가
- 추가적인 기능들 구현했습니다. 
(input focus,blur / 댓글 select 효과 / dayjs 댓글 시간 )

feat: 댓글 기능 추가

---

src/components/Detail/Comment/ReplyComment/index.tsx
src/components/Detail/Comment/comment.module.scss

댓글 닉네임 이미지 스타일 수정
- 이미지 스타일 수정

fix: 댓글 닉네임 이미지 스타일 수정

---

src/hooks/useComment.ts
src/hooks/useCommentReply.ts

eslint 수정
- eslint-disable-next-line no-console 추가
-

fix: eslint 수정

---

src/pages/Posting/Editor/index.tsx

fix: 린트 에러 수정

---

src/apis/posting.ts
src/hooks/usePosting.ts
src/pages/Category/category.module.scss
src/pages/Detail/index.tsx
src/pages/Posting/Editor/editor.module.scss
src/pages/Posting/Editor/index.tsx

[]
- 게시글 삭제를 구현
- 내가 쓴 글만 더보기 버튼 보이도록 수정
- 서버 요청 함수 hook으로 분리
-

feat: 게시글 삭제 구현 및 요청들 hook 으로 이동

---

src/components/Button/button.module.scss
src/components/Detail/Comment/comment.module.scss
src/components/Detail/DetailContent/detailContent.module.scss
src/components/Detail/DetailContent/index.tsx
src/components/Header/header.module.scss
src/components/Header/index.tsx
src/pages/Detail/detail.module.scss
src/pages/LocalAuth/index.tsx
src/pages/LocalAuth/localAuth.module.scss
src/pages/Signup/index.tsx
src/pages/Signup/signup.module.scss
src/pages/SignupComplete/index.tsx
src/types/index.d.ts

스타일 수정, detail 데이터 추가
- button font-weight 400 추가
- 회원가입, 동네설정 버튼 FloatingElem 변경
- header largeText (33px) 설정 추가
- datail페이지 : detailData 추가, 날짜 길게 나오는것, 스타일 요청사항 수정

fix: 스타일 수정, detail 데이터 추가

---

src/components/Detail/DetailContent/detailContent.module.scss
src/components/Detail/DetailContent/index.tsx
src/pages/Signup/index.tsx
src/pages/Signup/signup.module.scss

작성자 참여하기 버튼 disabeld, 회원가입 버튼 스타일 수정

fix: 작성자 참여하기 버튼 disabeld, 회원가입 버튼 스타일 수정

---

public/index.html

feat: OG 메타 태그 작성

---

public/index.html

fix: og image 비율 수정

---

src/pages/Detail/index.tsx

feat : detail 페이지 Spinner 추가

---

src/components/Layout/Layout.tsx
src/components/Layout/layout.module.scss
src/hooks/useProfile.ts
src/pages/LocalAuth/index.tsx
src/pages/LocalAuth/localAuth.module.scss

detail data refetch 추가, 스타일 수정
- detail 페이지 프로필 이미지 캐시 문제 해결
- 마이페이지 bg 수정 : 100vh, 100% 로도 해결이 안되서 inner에 백그라운드 주는걸로 해결했습니다.
- 동네설정 페이지 버튼 위치 수정 : flex에 margin-top:auto로 최대한 위치 조절했습니다.

fix: detail data refetch 추가, 스타일 수정

---

src/hooks/useApply.ts

fix: 오타 수정

---

src/pages/LocalAuth/index.tsx
src/pages/Signup/index.tsx

fix: 버튼 위치 수정

---

src/pages/LocalAuth/index.tsx
src/pages/Signup/index.tsx

fix: 버튼 위치 롤백
